baseURL = "https://www.spacelephant.org/"
languageCode = "en-us"
title = "Solutions for a decentralized economy | Space Elephant"
theme = "meghna"

DefaultContentLanguage = "en"

[languages]
    [languages.en]
        weight = 1

    [languages.fr]
        weight = 2
        title= "Solutions pour une économie décentralisée | Space Elephant"
        [languages.fr.params]
            home = "Home_FR"
            description = "Space Elephant, solutions pour un économie décentralisée"
            keywords = "blockchain, décentralisation, économie, space elephant, spacelephant"
            [languages.fr.params.og]
                url= "https://www.spacelephant.org/"
                site_name= "Space Elephant"
                image= "images/spacelephant-opengraph_fr.jpg"
                image_secrure_url="images/spacelephant-opengraph_fr.jpg"

            [languages.fr.params.twitter]
                image= "images/spacelephant-opengraph_fr.jpg"

            [languages.fr.params.banner]
                enable = true
                heading = "Space Elephant"
                logotitle = "images/title_only.png"
                logoonly = "images/logo_only.png"
                bgImage = "images/slider/wallpaper_SE.jpg"
                content= "Solutions pour l'économie décentralisée"
                btn = true
                btnText="En savoir plus"
                btnURL="#products"

            [languages.fr.params.footer]
                copyright = "Toutes les marques et copyrights reviennent à leurs propriétaires respectifs. Immatriculé #839193422 RCS Nantes, France"
                allrights = "Tous droits réservés"
                [languages.fr.params.footer.credits]
                templateUrl = "https://github.com/themefisher/meghna-hugo"
                templateName = "Meghna Template"
                creatorUrl = "https://github.com/themefisher"
                creatorName = "themefisher"
                [[languages.fr.params.footer.socialIcon]]
                icon = "fab fa-twitter"
                url = "https://twitter.com/spacelephant01"

                [[languages.fr.params.footer.socialIcon]]
                icon = "fab fa-medium-m"
                url = "https://medium.com/unik-name"

                [[languages.fr.params.footer.socialIcon]]
                icon = "fab fa-linkedin-in"
                url = "https://www.linkedin.com/company/spacelephant/"

                [[languages.fr.params.footer.socialIcon]]
                icon = "fab fa-github"
                url = "https://github.com/spacelephant"

                [[languages.fr.params.footer.socialIcon]]
                icon = "fas fa-flask"
                url = "https://github.com/spacelephantlabs"

# Site params
[params]
author= "Space Elephant"
description= "Space Elephant, solutions for a decentralized economy"
keywords= "blockchain, decentralization, economy, space elephant, spacelephant"

home= "Home"
logo = "images/logo_header.png"
logofooter = "images/logo_white.png"

# Google Analytics ID
gaid= "UA-115765369-1"

# Stylesheets
custom_css = ["css/style.css", "css/custom_se.css", "css/media-queries.css"]

# Custom scripts
custom_scripts = ["js/custom_se.js"]

    # Meta og
    [params.og]
    url= "https://www.spacelephant.org/"
    site_name= "Space Elephant"
    image= "images/spacelephant-opengraph.jpg"
    image_secrure_url="images/spacelephant-opengraph.jpg"

    # Meta Twitter
    [params.twitter]
    image= "images/homepage-screenshot.jpg"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/wallpaper_SE.jpg"
    # icon = "tf-ion-play"
    heading = "Space Elephant"
    logotitle = "images/title_only.png"
    logoonly = "images/logo_only.png"
    content= "Solutions for a decentralized economy"
    btn = true
    btnText="Explore Us"
    btnURL="#mission"

    # footer
    [params.footer]
        copyright = "All trademarks and copyrights belong to their respective owners. Incorporated #839193422 RCS Nantes, France"
        allrights = "All rights reserved"
        [params.footer.credits]
            templateUrl = "https://github.com/themefisher/meghna-hugo"
            templateName = "Meghna Template"
            creatorUrl = "https://github.com/themefisher"
            creatorName = "themefisher"
        [[params.footer.socialIcon]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/spacelephant01"

        [[params.footer.socialIcon]]
        icon = "fab fa-medium-m"
        url = "https://medium.com/unik-name"

        [[params.footer.socialIcon]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/company/spacelephant/"

        [[params.footer.socialIcon]]
        icon = "fab fa-github"
        url = "https://github.com/spacelephant"

        [[params.footer.socialIcon]]
        icon = "fas fa-flask"
        url = "https://github.com/spacelephantlabs"
